name: Generate Snake

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: jiminlyy
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#8EC5FC&color_dots=#EAF7FF,#D6EEFF,#BFE7FF,#8EC5FC,#5DADE2
